services:
  # Service 1: Backend (PHP-FPM)
  app:
    image: php:8.2-fpm
    container_name: php_backend_pos
    volumes:
      - ./:/var/www/html
    # Modifikasi baris ini agar PHP container otomatis menginstal driver MySQL saat dinyalakan
    command: bash -c "docker-php-ext-install mysqli && php-fpm"
    depends_on:
      - db

  # Service 2: Web Server (Nginx)
  nginx:
    image: nginx:alpine
    container_name: nginx_frontend_pos
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app

  # Service 3: Database Resmi (MySQL 8.0)
  db:
    image: mysql:8.0
    container_name: mysql_database
    environment:
      MYSQL_ROOT_PASSWORD: rootdb
      MYSQL_DATABASE: db_pos
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin_pos
    environment:
      PMA_HOST: db                 # Nama service database
      PMA_PORT: 3306               # Port database
      PMA_ARBITRARY: 1             # Izinkan koneksi ke server lain
      UPLOAD_LIMIT: 100M           # Batas upload file
    ports:
      - "81:80"                  # Akses via localhost:8080
    depends_on:
      - db
    restart: unless-stopped

# Membuat penyimpanan persisten agar data di MySQL tidak hilang saat container dimatikan
volumes:
  mysql_data: