server {
    listen 80; # Kamu bisa pakai port 80 atau 8080 bebas
    server_name localhost;

    # Arahkan ke folder tempat kamu menyimpan file index.html, script.js, dan data.php
    root /var/www/html/public; 
    index index.html index.php;

    # Handle file frontend statis (HTML, JS, CSS)
    location / {
        try_files $uri $uri/ =404;
    }


    location ~ \.php$ {
    include fastcgi_params;
    fastcgi_pass app:9000;

    fastcgi_index index.php;
    fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
}
}