server {
    listen 80;
    server_name localhost;

    root /var/www/html/public; 
    index index.html index.php;

    # Handle file frontend statis
    location / {
        try_files $uri $uri/ =404;
    }

    # Tambahkan blok ini untuk menangkap semua URL /api/
    location /api/ {
        try_files $uri $uri/ /api/index.php?$args;
    }

    # Handle eksekusi file PHP
    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_pass app:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }
}